### ISSUE TITLE
Great Library! - Windows timing question ?

### ISSUE THREAD

**Issue by Percell007** [DFHack/clsocket#12]
Hello Mark,
The clsocket library looks well structured and suited to handle many socket applications in one shot.
I like it a lot!
I also like the abundance of comments ! Fantastic !
Just one question:
In the CStatTimer class I see you don't QueryPerformanceFrequency for WIN32.
How do you get accurate time based counts without doing that ? Whats the secret ?
The way understand QueryPerformanceCounter just gets a count/tick...but you need to combine it with the Frequency to get a time based count ?
Thanks & Cheers

**Comment by lethosor** [comment]
None of us are Mark. This repo is mostly to support DFHack, although I'm not aware of another place where it's hosted currently. From looking at the CStatTimer class, I don't think it works correctly on Windows if what you said is correct. It also doesn't appear to be used internally anywhere - CSimpleSocket has a timer instance, but it appears to be used only for profiling, and I'm not sure if even that data is exposed anywhere (a bit hard to investigate on mobile).
