### ISSUE TITLE
Include example covering error handling

### ISSUE THREAD

**Issue by TheGreatRambler** [DFHack/clsocket#16]
Using a simple:
```c
networkConnection->TranslateSocketError();
CSimpleSocket::CSocketError e = networkConnection->GetSocketError();
networkConnection->DescribeError(e);
```
Has seemed to error every time. Also, I've been getting -1 from networkConnection->Receive() and when checking the error using the above code, the error is `CSimpleSocket::CSocketError::SocketSuccess`.

**Comment by lethosor** [comment]
What OS? Might need a larger code snippet than that - how is the snippet you posted failing?

**Comment by TheGreatRambler** [comment]
Nintendo Switch. Yes, Nintendo Switch. I've been able to get it to work in the past, but I've recently broken my network implementation by adding stricter error handling. I'll get back to you with my code.

**Comment by lethosor** [comment]
Huh. Looks like that's BSD-based? If it has the BSD networking syscalls that this library needs, I guess it makes sense that it would work, but it's unlikely that any of us would be able to test on it.

**Comment by TheGreatRambler** [comment]
The errors I were encountering were unrelated, turns out I'm dumb. I've had to doctor this lib a bit to get it working with switch homebrew, by the way, but it works fantastic! Love the cpp approach to sockets.

**Comment by lethosor** [comment]
It happens; glad it's useful! (We didn't write it originally, but it's simple enough for DFHack that we've kept it around.)
